"""add username column to users

Revision ID: 0737f55ad53c
Revises: 5779da000de3
Create Date: 2026-06-24 17:01:11.151863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0737f55ad53c'
down_revision: Union[str, Sequence[str], None] = '5779da000de3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('username', sa.String(), nullable=False))
    op.drop_constraint(op.f('Users_name_key'), 'Users', type_='unique')
    op.create_unique_constraint(None, 'Users', ['email'])
    op.create_unique_constraint(None, 'Users', ['username'])
    op.drop_column('Users', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Users', type_='unique')
    op.drop_constraint(None, 'Users', type_='unique')
    op.create_unique_constraint(op.f('Users_name_key'), 'Users', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('Users', 'username')
    # ### end Alembic commands ###
