"""fix column name typo

Revision ID: 5779da000de3
Revises: 8456a91aa21e
Create Date: 2026-06-21 14:41:44.201189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5779da000de3'
down_revision: Union[str, Sequence[str], None] = '8456a91aa21e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Trips', sa.Column('start_odometer', sa.Integer(), nullable=False))
    op.add_column('Trips', sa.Column('end_odometer', sa.Integer(), nullable=False))
    op.drop_column('Trips', 'end_oddomoter')
    op.drop_column('Trips', 'start_oddometer')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Trips', sa.Column('start_oddometer', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('Trips', sa.Column('end_oddomoter', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('Trips', 'end_odometer')
    op.drop_column('Trips', 'start_odometer')
    # ### end Alembic commands ###
