"""added foreign key to Trips in order to query

Revision ID: 6c01cb55972a
Revises: 0737f55ad53c
Create Date: 2026-06-28 22:16:57.323309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c01cb55972a'
down_revision: Union[str, Sequence[str], None] = '0737f55ad53c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Trips', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Trips', 'Users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Trips', type_='foreignkey')
    op.drop_column('Trips', 'user_id')
    # ### end Alembic commands ###
